#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
/* automatically generated by rust-bindgen 0.72.1 */

pub const TRUE: i32 = 1;
pub const FALSE: i32 = 0;
pub const IMAQDX_MAX_API_STRING_LENGTH: i32 = 512;
pub const IMAQDX_TIMEOUT_INFINITE: i32 = -1;
pub const IMAQDX_TIMEOUT_USE_DRIVER_SETTING: i32 = -2;
pub const IMAQdxAttributeBaseAddress: &[u8; 31] = b"CameraInformation::BaseAddress\0";
pub const IMAQdxAttributeBusType: &[u8; 27] = b"CameraInformation::BusType\0";
pub const IMAQdxAttributeModelName: &[u8; 29] = b"CameraInformation::ModelName\0";
pub const IMAQdxAttributeSerialNumberHigh: &[u8; 36] = b"CameraInformation::SerialNumberHigh\0";
pub const IMAQdxAttributeSerialNumberLow: &[u8; 35] = b"CameraInformation::SerialNumberLow\0";
pub const IMAQdxAttributeVendorName: &[u8; 30] = b"CameraInformation::VendorName\0";
pub const IMAQdxAttributeHostIPAddress: &[u8; 33] = b"CameraInformation::HostIPAddress\0";
pub const IMAQdxAttributeIPAddress: &[u8; 29] = b"CameraInformation::IPAddress\0";
pub const IMAQdxAttributePrimaryURLString: &[u8; 36] = b"CameraInformation::PrimaryURLString\0";
pub const IMAQdxAttributeSecondaryURLString: &[u8; 38] = b"CameraInformation::SecondaryURLString\0";
pub const IMAQdxAttributeAcqInProgress: &[u8; 33] = b"StatusInformation::AcqInProgress\0";
pub const IMAQdxAttributeLastBufferCount: &[u8; 35] = b"StatusInformation::LastBufferCount\0";
pub const IMAQdxAttributeLastBufferNumber: &[u8; 36] = b"StatusInformation::LastBufferNumber\0";
pub const IMAQdxAttributeLostBufferCount: &[u8; 35] = b"StatusInformation::LostBufferCount\0";
pub const IMAQdxAttributeLostPacketCount: &[u8; 35] = b"StatusInformation::LostPacketCount\0";
pub const IMAQdxAttributeRequestedResendPackets: &[u8; 46] =
	b"StatusInformation::RequestedResendPacketCount\0";
pub const IMAQdxAttributeReceivedResendPackets: &[u8; 41] =
	b"StatusInformation::ReceivedResendPackets\0";
pub const IMAQdxAttributeHandledEventCount: &[u8; 37] = b"StatusInformation::HandledEventCount\0";
pub const IMAQdxAttributeLostEventCount: &[u8; 34] = b"StatusInformation::LostEventCount\0";
pub const IMAQdxAttributeBayerGainB: &[u8; 36] = b"AcquisitionAttributes::Bayer::GainB\0";
pub const IMAQdxAttributeBayerGainG: &[u8; 36] = b"AcquisitionAttributes::Bayer::GainG\0";
pub const IMAQdxAttributeBayerGainR: &[u8; 36] = b"AcquisitionAttributes::Bayer::GainR\0";
pub const IMAQdxAttributeBayerPattern: &[u8; 38] = b"AcquisitionAttributes::Bayer::Pattern\0";
pub const IMAQdxAttributeStreamChannelMode: &[u8; 53] =
	b"AcquisitionAttributes::Controller::StreamChannelMode\0";
pub const IMAQdxAttributeDesiredStreamChannel: &[u8; 56] =
	b"AcquisitionAttributes::Controller::DesiredStreamChannel\0";
pub const IMAQdxAttributeFrameInterval: &[u8; 37] = b"AcquisitionAttributes::FrameInterval\0";
pub const IMAQdxAttributeIgnoreFirstFrame: &[u8; 40] = b"AcquisitionAttributes::IgnoreFirstFrame\0";
pub const IMAQdxAttributeOffsetX: &[u8; 8] = b"OffsetX\0";
pub const IMAQdxAttributeOffsetY: &[u8; 8] = b"OffsetY\0";
pub const IMAQdxAttributeWidth: &[u8; 6] = b"Width\0";
pub const IMAQdxAttributeHeight: &[u8; 7] = b"Height\0";
pub const IMAQdxAttributePixelFormat: &[u8; 12] = b"PixelFormat\0";
pub const IMAQdxAttributePacketSize: &[u8; 11] = b"PacketSize\0";
pub const IMAQdxAttributePayloadSize: &[u8; 12] = b"PayloadSize\0";
pub const IMAQdxAttributeSpeed: &[u8; 29] = b"AcquisitionAttributes::Speed\0";
pub const IMAQdxAttributeShiftPixelBits: &[u8; 38] = b"AcquisitionAttributes::ShiftPixelBits\0";
pub const IMAQdxAttributeSwapPixelBytes: &[u8; 38] = b"AcquisitionAttributes::SwapPixelBytes\0";
pub const IMAQdxAttributeOverwriteMode: &[u8; 37] = b"AcquisitionAttributes::OverwriteMode\0";
pub const IMAQdxAttributeTimeout: &[u8; 31] = b"AcquisitionAttributes::Timeout\0";
pub const IMAQdxAttributeVideoMode: &[u8; 33] = b"AcquisitionAttributes::VideoMode\0";
pub const IMAQdxAttributeBitsPerPixel: &[u8; 36] = b"AcquisitionAttributes::BitsPerPixel\0";
pub const IMAQdxAttributePixelSignedness: &[u8; 39] = b"AcquisitionAttributes::PixelSignedness\0";
pub const IMAQdxAttributeReserveDualPackets: &[u8; 42] =
	b"AcquisitionAttributes::ReserveDualPackets\0";
pub const IMAQdxAttributeReceiveTimestampMode: &[u8; 44] =
	b"AcquisitionAttributes::ReceiveTimestampMode\0";
pub const IMAQdxAttributeActualPeakBandwidth: &[u8; 79] =
	b"AcquisitionAttributes::AdvancedEthernet::BandwidthControl::ActualPeakBandwidth\0";
pub const IMAQdxAttributeDesiredPeakBandwidth: &[u8; 80] =
	b"AcquisitionAttributes::AdvancedEthernet::BandwidthControl::DesiredPeakBandwidth\0";
pub const IMAQdxAttributeDestinationMode: &[u8; 69] =
	b"AcquisitionAttributes::AdvancedEthernet::Controller::DestinationMode\0";
pub const IMAQdxAttributeDestinationMulticastAddress: &[u8; 81] =
	b"AcquisitionAttributes::AdvancedEthernet::Controller::DestinationMulticastAddress\0";
pub const IMAQdxAttributeEventsEnabled: &[u8; 72] =
	b"AcquisitionAttributes::AdvancedEthernet::EventParameters::EventsEnabled\0";
pub const IMAQdxAttributeMaxOutstandingEvents: &[u8; 79] =
	b"AcquisitionAttributes::AdvancedEthernet::EventParameters::MaxOutstandingEvents\0";
pub const IMAQdxAttributeTestPacketEnabled: &[u8; 81] =
	b"AcquisitionAttributes::AdvancedEthernet::TestPacketParameters::TestPacketEnabled\0";
pub const IMAQdxAttributeTestPacketTimeout: &[u8; 81] =
	b"AcquisitionAttributes::AdvancedEthernet::TestPacketParameters::TestPacketTimeout\0";
pub const IMAQdxAttributeMaxTestPacketRetries: &[u8; 84] =
	b"AcquisitionAttributes::AdvancedEthernet::TestPacketParameters::MaxTestPacketRetries\0";
pub const IMAQdxAttributeChunkDataDecodingEnabled: &[u8; 67] =
	b"AcquisitionAttributes::ChunkDataDecoding::ChunkDataDecodingEnabled\0";
pub const IMAQdxAttributeChunkDataDecodingMaxElementSize: &[u8; 63] =
	b"AcquisitionAttributes::ChunkDataDecoding::MaximumChunkCopySize\0";
pub const IMAQdxAttributeLostPacketMode: &[u8; 56] =
	b"AcquisitionAttributes::AdvancedEthernet::LostPacketMode\0";
pub const IMAQdxAttributeMemoryWindowSize: &[u8; 76] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::MemoryWindowSize\0";
pub const IMAQdxAttributeResendsEnabled: &[u8; 74] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::ResendsEnabled\0";
pub const IMAQdxAttributeResendThresholdPercentage: &[u8; 85] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::ResendThresholdPercentage\0";
pub const IMAQdxAttributeResendBatchingPercentage: &[u8; 84] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::ResendBatchingPercentage\0";
pub const IMAQdxAttributeMaxResendsPerPacket: &[u8; 79] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::MaxResendsPerPacket\0";
pub const IMAQdxAttributeResendResponseTimeout: &[u8; 81] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::ResendResponseTimeout\0";
pub const IMAQdxAttributeNewPacketTimeout: &[u8; 76] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::NewPacketTimeout\0";
pub const IMAQdxAttributeMissingPacketTimeout: &[u8; 80] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::MissingPacketTimeout\0";
pub const IMAQdxAttributeResendTimerResolution: &[u8; 81] =
	b"AcquisitionAttributes::AdvancedEthernet::ResendParameters::ResendTimerResolution\0";
pub type uInt8 = ::std::os::raw::c_uchar;
pub type uInt16 = ::std::os::raw::c_ushort;
pub type uInt32 = ::std::os::raw::c_ulong;
pub type uInt64 = ::std::os::raw::c_ulonglong;
pub type Int8 = ::std::os::raw::c_char;
pub type Int16 = ::std::os::raw::c_short;
pub type Int32 = ::std::os::raw::c_long;
pub type Int64 = ::std::os::raw::c_longlong;
pub type float32 = f32;
pub type float64 = f64;
pub type GUIHNDL = uInt32;
pub type bool32 = uInt32;
pub type IMAQdxSession = uInt32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Image_struct {
	_unused: [u8; 0],
}
pub type Image = Image_struct;
pub const IMAQdxBusType_enum_IMAQdxBusTypeFireWire: IMAQdxBusType_enum = 825440564;
pub const IMAQdxBusType_enum_IMAQdxBusTypeEthernet: IMAQdxBusType_enum = 1768977972;
pub const IMAQdxBusType_enum_IMAQdxBusTypeSimulator: IMAQdxBusType_enum = 544434541;
pub const IMAQdxBusType_enum_IMAQdxBusTypeDirectShow: IMAQdxBusType_enum = 1685284983;
pub const IMAQdxBusType_enum_IMAQdxBusTypeIP: IMAQdxBusType_enum = 1230005101;
pub const IMAQdxBusType_enum_IMAQdxBusTypeSmartCam2: IMAQdxBusType_enum = 1396924722;
pub const IMAQdxBusType_enum_IMAQdxBusTypeUSB3Vision: IMAQdxBusType_enum = 1431519795;
pub const IMAQdxBusType_enum_IMAQdxBusTypeUVC: IMAQdxBusType_enum = 1431716640;
pub const IMAQdxBusType_enum_IMAQdxBusTypeISC: IMAQdxBusType_enum = 1230193440;
pub const IMAQdxBusType_enum_IMAQdxBusTypeCameraLink: IMAQdxBusType_enum = 1129074251;
pub const IMAQdxBusType_enum_IMAQdxBusTypePCIePXIe: IMAQdxBusType_enum = 1346586981;
pub const IMAQdxBusType_enum_IMAQdxBusTypeCXP: IMAQdxBusType_enum = 1129861152;
pub const IMAQdxBusType_enum_IMAQdxBusTypeGuard: IMAQdxBusType_enum = -1;
pub type IMAQdxBusType_enum = ::std::os::raw::c_int;
pub use self::IMAQdxBusType_enum as IMAQdxBusType;
pub const IMAQdxCameraControlMode_enum_IMAQdxCameraControlModeController:
	IMAQdxCameraControlMode_enum = 0;
pub const IMAQdxCameraControlMode_enum_IMAQdxCameraControlModeListener:
	IMAQdxCameraControlMode_enum = 1;
pub const IMAQdxCameraControlMode_enum_IMAQdxCameraControlModeGuard: IMAQdxCameraControlMode_enum =
	-1;
pub type IMAQdxCameraControlMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxCameraControlMode_enum as IMAQdxCameraControlMode;
pub const IMAQdxBufferNumberMode_enum_IMAQdxBufferNumberModeNext: IMAQdxBufferNumberMode_enum = 0;
pub const IMAQdxBufferNumberMode_enum_IMAQdxBufferNumberModeLast: IMAQdxBufferNumberMode_enum = 1;
pub const IMAQdxBufferNumberMode_enum_IMAQdxBufferNumberModeBufferNumber:
	IMAQdxBufferNumberMode_enum = 2;
pub const IMAQdxBufferNumberMode_enum_IMAQdxBufferNumberModeEvery: IMAQdxBufferNumberMode_enum = 3;
pub const IMAQdxBufferNumberMode_enum_IMAQdxBufferNumberModeLastNew: IMAQdxBufferNumberMode_enum =
	4;
pub const IMAQdxBufferNumberMode_enum_IMAQdxBufferNumberModeGuard: IMAQdxBufferNumberMode_enum = -1;
pub type IMAQdxBufferNumberMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxBufferNumberMode_enum as IMAQdxBufferNumberMode;
pub const IMAQdxPnpEvent_enum_IMAQdxPnpEventCameraAttached: IMAQdxPnpEvent_enum = 0;
pub const IMAQdxPnpEvent_enum_IMAQdxPnpEventCameraDetached: IMAQdxPnpEvent_enum = 1;
pub const IMAQdxPnpEvent_enum_IMAQdxPnpEventBusReset: IMAQdxPnpEvent_enum = 2;
pub const IMAQdxPnpEvent_enum_IMAQdxPnpEventGuard: IMAQdxPnpEvent_enum = -1;
pub type IMAQdxPnpEvent_enum = ::std::os::raw::c_int;
pub use self::IMAQdxPnpEvent_enum as IMAQdxPnpEvent;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternNone: IMAQdxBayerPattern_enum = 0;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternGB: IMAQdxBayerPattern_enum = 1;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternGR: IMAQdxBayerPattern_enum = 2;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternBG: IMAQdxBayerPattern_enum = 3;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternRG: IMAQdxBayerPattern_enum = 4;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternHardware: IMAQdxBayerPattern_enum = 5;
pub const IMAQdxBayerPattern_enum_IMAQdxBayerPatternGuard: IMAQdxBayerPattern_enum = -1;
pub type IMAQdxBayerPattern_enum = ::std::os::raw::c_int;
pub use self::IMAQdxBayerPattern_enum as IMAQdxBayerPattern;
pub const IMAQdxBayerAlgorithm_enum_IMAQdxBayerAlgorithmBilinear: IMAQdxBayerAlgorithm_enum = 0;
pub const IMAQdxBayerAlgorithm_enum_IMAQdxBayerAlgorithmVNG: IMAQdxBayerAlgorithm_enum = 1;
pub const IMAQdxBayerAlgorithm_enum_IMAQdxBayerAlgorithmGuard: IMAQdxBayerAlgorithm_enum = -1;
pub type IMAQdxBayerAlgorithm_enum = ::std::os::raw::c_int;
pub use self::IMAQdxBayerAlgorithm_enum as IMAQdxBayerAlgorithm;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeU8: IMAQdxOutputImageType_enum = 0;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeI16: IMAQdxOutputImageType_enum = 1;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeU16: IMAQdxOutputImageType_enum = 7;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeRGB32: IMAQdxOutputImageType_enum = 4;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeRGB64: IMAQdxOutputImageType_enum = 6;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeAuto: IMAQdxOutputImageType_enum =
	2147483647;
pub const IMAQdxOutputImageType_enum_IMAQdxOutputImageTypeGuard: IMAQdxOutputImageType_enum = -1;
pub type IMAQdxOutputImageType_enum = ::std::os::raw::c_int;
pub use self::IMAQdxOutputImageType_enum as IMAQdxOutputImageType;
pub const IMAQdxDestinationMode_enum_IMAQdxDestinationModeUnicast: IMAQdxDestinationMode_enum = 0;
pub const IMAQdxDestinationMode_enum_IMAQdxDestinationModeBroadcast: IMAQdxDestinationMode_enum = 1;
pub const IMAQdxDestinationMode_enum_IMAQdxDestinationModeMulticast: IMAQdxDestinationMode_enum = 2;
pub const IMAQdxDestinationMode_enum_IMAQdxDestinationModeGuard: IMAQdxDestinationMode_enum = -1;
pub type IMAQdxDestinationMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxDestinationMode_enum as IMAQdxDestinationMode;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeU32: IMAQdxAttributeType_enum = 0;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeI64: IMAQdxAttributeType_enum = 1;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeF64: IMAQdxAttributeType_enum = 2;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeString: IMAQdxAttributeType_enum = 3;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeEnum: IMAQdxAttributeType_enum = 4;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeBool: IMAQdxAttributeType_enum = 5;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeCommand: IMAQdxAttributeType_enum = 6;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeBlob: IMAQdxAttributeType_enum = 7;
pub const IMAQdxAttributeType_enum_IMAQdxAttributeTypeGuard: IMAQdxAttributeType_enum = -1;
pub type IMAQdxAttributeType_enum = ::std::os::raw::c_int;
pub use self::IMAQdxAttributeType_enum as IMAQdxAttributeType;
pub const IMAQdxValueType_enum_IMAQdxValueTypeU32: IMAQdxValueType_enum = 0;
pub const IMAQdxValueType_enum_IMAQdxValueTypeI64: IMAQdxValueType_enum = 1;
pub const IMAQdxValueType_enum_IMAQdxValueTypeF64: IMAQdxValueType_enum = 2;
pub const IMAQdxValueType_enum_IMAQdxValueTypeString: IMAQdxValueType_enum = 3;
pub const IMAQdxValueType_enum_IMAQdxValueTypeEnumItem: IMAQdxValueType_enum = 4;
pub const IMAQdxValueType_enum_IMAQdxValueTypeBool: IMAQdxValueType_enum = 5;
pub const IMAQdxValueType_enum_IMAQdxValueTypeDisposableString: IMAQdxValueType_enum = 6;
pub const IMAQdxValueType_enum_IMAQdxValueTypeGuard: IMAQdxValueType_enum = -1;
pub type IMAQdxValueType_enum = ::std::os::raw::c_int;
pub use self::IMAQdxValueType_enum as IMAQdxValueType;
pub const IMAQdxInterfaceFileFlags_enum_IMAQdxInterfaceFileFlagsConnected:
	IMAQdxInterfaceFileFlags_enum = 1;
pub const IMAQdxInterfaceFileFlags_enum_IMAQdxInterfaceFileFlagsDirty:
	IMAQdxInterfaceFileFlags_enum = 2;
pub const IMAQdxInterfaceFileFlags_enum_IMAQdxInterfaceFileFlagsGuard:
	IMAQdxInterfaceFileFlags_enum = -1;
pub type IMAQdxInterfaceFileFlags_enum = ::std::os::raw::c_int;
pub use self::IMAQdxInterfaceFileFlags_enum as IMAQdxInterfaceFileFlags;
pub const IMAQdxOverwriteMode_enum_IMAQdxOverwriteModeGetOldest: IMAQdxOverwriteMode_enum = 0;
pub const IMAQdxOverwriteMode_enum_IMAQdxOverwriteModeFail: IMAQdxOverwriteMode_enum = 2;
pub const IMAQdxOverwriteMode_enum_IMAQdxOverwriteModeGetNewest: IMAQdxOverwriteMode_enum = 3;
pub const IMAQdxOverwriteMode_enum_IMAQdxOverwriteModeGuard: IMAQdxOverwriteMode_enum = -1;
pub type IMAQdxOverwriteMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxOverwriteMode_enum as IMAQdxOverwriteMode;
pub const IMAQdxIncompleteBufferMode_enum_IMAQdxIncompleteBufferModeIgnore:
	IMAQdxIncompleteBufferMode_enum = 0;
pub const IMAQdxIncompleteBufferMode_enum_IMAQdxIncompleteBufferModeFail:
	IMAQdxIncompleteBufferMode_enum = 1;
pub const IMAQdxIncompleteBufferMode_enum_IMAQdxIncompleteBufferModeGuard:
	IMAQdxIncompleteBufferMode_enum = -1;
pub type IMAQdxIncompleteBufferMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxIncompleteBufferMode_enum as IMAQdxIncompleteBufferMode;
pub const IMAQdxLostPacketMode_enum_IMAQdxLostPacketModeIgnore: IMAQdxLostPacketMode_enum = 0;
pub const IMAQdxLostPacketMode_enum_IMAQdxLostPacketModeFail: IMAQdxLostPacketMode_enum = 1;
pub const IMAQdxLostPacketMode_enum_IMAQdxLostPacketModeGuard: IMAQdxLostPacketMode_enum = -1;
pub type IMAQdxLostPacketMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxLostPacketMode_enum as IMAQdxLostPacketMode;
pub const IMAQdxAttributeVisibility_enum_IMAQdxAttributeVisibilitySimple:
	IMAQdxAttributeVisibility_enum = 4096;
pub const IMAQdxAttributeVisibility_enum_IMAQdxAttributeVisibilityIntermediate:
	IMAQdxAttributeVisibility_enum = 8192;
pub const IMAQdxAttributeVisibility_enum_IMAQdxAttributeVisibilityAdvanced:
	IMAQdxAttributeVisibility_enum = 16384;
pub const IMAQdxAttributeVisibility_enum_IMAQdxAttributeVisibilityGuard:
	IMAQdxAttributeVisibility_enum = -1;
pub type IMAQdxAttributeVisibility_enum = ::std::os::raw::c_int;
pub use self::IMAQdxAttributeVisibility_enum as IMAQdxAttributeVisibility;
pub const IMAQdxStreamChannelMode_enum_IMAQdxStreamChannelModeAutomatic:
	IMAQdxStreamChannelMode_enum = 0;
pub const IMAQdxStreamChannelMode_enum_IMAQdxStreamChannelModeManual: IMAQdxStreamChannelMode_enum =
	1;
pub const IMAQdxStreamChannelMode_enum_IMAQdxStreamChannelModeGuard: IMAQdxStreamChannelMode_enum =
	-1;
pub type IMAQdxStreamChannelMode_enum = ::std::os::raw::c_int;
pub use self::IMAQdxStreamChannelMode_enum as IMAQdxStreamChannelMode;
pub const IMAQdxPixelSignedness_enum_IMAQdxPixelSignednessUnsigned: IMAQdxPixelSignedness_enum = 0;
pub const IMAQdxPixelSignedness_enum_IMAQdxPixelSignednessSigned: IMAQdxPixelSignedness_enum = 1;
pub const IMAQdxPixelSignedness_enum_IMAQdxPixelSignednessHardware: IMAQdxPixelSignedness_enum = 2;
pub const IMAQdxPixelSignedness_enum_IMAQdxPixelSignednessGuard: IMAQdxPixelSignedness_enum = -1;
pub type IMAQdxPixelSignedness_enum = ::std::os::raw::c_int;
pub use self::IMAQdxPixelSignedness_enum as IMAQdxPixelSignedness;
pub const IMAQdxUSBConnectionSpeed_enum_IMAQdxUSBConnectionSpeedLow: IMAQdxUSBConnectionSpeed_enum =
	1;
pub const IMAQdxUSBConnectionSpeed_enum_IMAQdxUSBConnectionSpeedFull:
	IMAQdxUSBConnectionSpeed_enum = 2;
pub const IMAQdxUSBConnectionSpeed_enum_IMAQdxUSBConnectionSpeedHigh:
	IMAQdxUSBConnectionSpeed_enum = 4;
pub const IMAQdxUSBConnectionSpeed_enum_IMAQdxUSBConnectionSpeedSuper:
	IMAQdxUSBConnectionSpeed_enum = 8;
pub const IMAQdxUSBConnectionSpeed_enum_IMAQdxUSBConnectionSpeedGuard:
	IMAQdxUSBConnectionSpeed_enum = -1;
pub type IMAQdxUSBConnectionSpeed_enum = ::std::os::raw::c_int;
pub use self::IMAQdxUSBConnectionSpeed_enum as IMAQdxUSBConnectionSpeed;
pub const IMAQdxDefaultPersistenceAlgorithm_enum_IMAQdxPersistenceAlgorithmAuto:
	IMAQdxDefaultPersistenceAlgorithm_enum = 0;
pub const IMAQdxDefaultPersistenceAlgorithm_enum_IMAQdxPersistenceAlgorithmIMAQdx:
	IMAQdxDefaultPersistenceAlgorithm_enum = 1;
pub const IMAQdxDefaultPersistenceAlgorithm_enum_IMAQdxPersistenceAlgorithmGenICam:
	IMAQdxDefaultPersistenceAlgorithm_enum = 2;
pub const IMAQdxDefaultPersistenceAlgorithm_enum_IMAQdxPersistenceAlgorithmGuard:
	IMAQdxDefaultPersistenceAlgorithm_enum = -1;
pub type IMAQdxDefaultPersistenceAlgorithm_enum = ::std::os::raw::c_int;
pub use self::IMAQdxDefaultPersistenceAlgorithm_enum as IMAQdxDefaultPersistenceAlgorithm;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMAQdxCameraInformation_struct {
	pub Type: uInt32,
	pub Version: uInt32,
	pub Flags: uInt32,
	pub SerialNumberHi: uInt32,
	pub SerialNumberLo: uInt32,
	pub BusType: IMAQdxBusType,
	pub InterfaceName: [::std::os::raw::c_char; 512usize],
	pub VendorName: [::std::os::raw::c_char; 512usize],
	pub ModelName: [::std::os::raw::c_char; 512usize],
	pub CameraFileName: [::std::os::raw::c_char; 512usize],
	pub CameraAttributeURL: [::std::os::raw::c_char; 512usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of IMAQdxCameraInformation_struct"]
		[::std::mem::size_of::<IMAQdxCameraInformation_struct>() - 2584usize];
	["Alignment of IMAQdxCameraInformation_struct"]
		[::std::mem::align_of::<IMAQdxCameraInformation_struct>() - 4usize];
	["Offset of field: IMAQdxCameraInformation_struct::Type"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, Type) - 0usize];
	["Offset of field: IMAQdxCameraInformation_struct::Version"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, Version) - 4usize];
	["Offset of field: IMAQdxCameraInformation_struct::Flags"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, Flags) - 8usize];
	["Offset of field: IMAQdxCameraInformation_struct::SerialNumberHi"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, SerialNumberHi) - 12usize];
	["Offset of field: IMAQdxCameraInformation_struct::SerialNumberLo"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, SerialNumberLo) - 16usize];
	["Offset of field: IMAQdxCameraInformation_struct::BusType"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, BusType) - 20usize];
	["Offset of field: IMAQdxCameraInformation_struct::InterfaceName"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, InterfaceName) - 24usize];
	["Offset of field: IMAQdxCameraInformation_struct::VendorName"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, VendorName) - 536usize];
	["Offset of field: IMAQdxCameraInformation_struct::ModelName"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, ModelName) - 1048usize];
	["Offset of field: IMAQdxCameraInformation_struct::CameraFileName"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, CameraFileName) - 1560usize];
	["Offset of field: IMAQdxCameraInformation_struct::CameraAttributeURL"]
		[::std::mem::offset_of!(IMAQdxCameraInformation_struct, CameraAttributeURL) - 2072usize];
};
pub type IMAQdxCameraInformation = IMAQdxCameraInformation_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMAQdxCameraFile_struct {
	pub Type: uInt32,
	pub Version: uInt32,
	pub FileName: [::std::os::raw::c_char; 512usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of IMAQdxCameraFile_struct"]
		[::std::mem::size_of::<IMAQdxCameraFile_struct>() - 520usize];
	["Alignment of IMAQdxCameraFile_struct"]
		[::std::mem::align_of::<IMAQdxCameraFile_struct>() - 4usize];
	["Offset of field: IMAQdxCameraFile_struct::Type"]
		[::std::mem::offset_of!(IMAQdxCameraFile_struct, Type) - 0usize];
	["Offset of field: IMAQdxCameraFile_struct::Version"]
		[::std::mem::offset_of!(IMAQdxCameraFile_struct, Version) - 4usize];
	["Offset of field: IMAQdxCameraFile_struct::FileName"]
		[::std::mem::offset_of!(IMAQdxCameraFile_struct, FileName) - 8usize];
};
pub type IMAQdxCameraFile = IMAQdxCameraFile_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMAQdxAttributeInformation_struct {
	pub Type: IMAQdxAttributeType,
	pub Readable: bool32,
	pub Writable: bool32,
	pub Name: [::std::os::raw::c_char; 512usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of IMAQdxAttributeInformation_struct"]
		[::std::mem::size_of::<IMAQdxAttributeInformation_struct>() - 524usize];
	["Alignment of IMAQdxAttributeInformation_struct"]
		[::std::mem::align_of::<IMAQdxAttributeInformation_struct>() - 4usize];
	["Offset of field: IMAQdxAttributeInformation_struct::Type"]
		[::std::mem::offset_of!(IMAQdxAttributeInformation_struct, Type) - 0usize];
	["Offset of field: IMAQdxAttributeInformation_struct::Readable"]
		[::std::mem::offset_of!(IMAQdxAttributeInformation_struct, Readable) - 4usize];
	["Offset of field: IMAQdxAttributeInformation_struct::Writable"]
		[::std::mem::offset_of!(IMAQdxAttributeInformation_struct, Writable) - 8usize];
	["Offset of field: IMAQdxAttributeInformation_struct::Name"]
		[::std::mem::offset_of!(IMAQdxAttributeInformation_struct, Name) - 12usize];
};
pub type IMAQdxAttributeInformation = IMAQdxAttributeInformation_struct;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct IMAQdxEnumItem_struct {
	pub Value: uInt32,
	pub Reserved: uInt32,
	pub Name: [::std::os::raw::c_char; 512usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
	["Size of IMAQdxEnumItem_struct"][::std::mem::size_of::<IMAQdxEnumItem_struct>() - 520usize];
	["Alignment of IMAQdxEnumItem_struct"]
		[::std::mem::align_of::<IMAQdxEnumItem_struct>() - 4usize];
	["Offset of field: IMAQdxEnumItem_struct::Value"]
		[::std::mem::offset_of!(IMAQdxEnumItem_struct, Value) - 0usize];
	["Offset of field: IMAQdxEnumItem_struct::Reserved"]
		[::std::mem::offset_of!(IMAQdxEnumItem_struct, Reserved) - 4usize];
	["Offset of field: IMAQdxEnumItem_struct::Name"]
		[::std::mem::offset_of!(IMAQdxEnumItem_struct, Name) - 8usize];
};
pub type IMAQdxEnumItem = IMAQdxEnumItem_struct;
pub type IMAQdxVideoMode = IMAQdxEnumItem;
pub const IMAQdxIOSignalType_enum_IMAQdxIOSignalTypeTTL: IMAQdxIOSignalType_enum = 0;
pub const IMAQdxIOSignalType_enum_IMAQdxIOSignalTypeRTSI: IMAQdxIOSignalType_enum = 1;
pub const IMAQdxIOSignalType_enum_IMAQdxIOSignalTypeIsoIn: IMAQdxIOSignalType_enum = 2;
pub const IMAQdxIOSignalType_enum_IMAQdxIOSignalTypeIsoOut: IMAQdxIOSignalType_enum = 3;
pub const IMAQdxIOSignalType_enum_IMAQdxIOSignalTypeGuard: IMAQdxIOSignalType_enum = -1;
pub type IMAQdxIOSignalType_enum = ::std::os::raw::c_int;
pub use self::IMAQdxIOSignalType_enum as IMAQdxIOSignalType;
pub const IMAQdxEdge_enum_IMAQdxEdgeRising: IMAQdxEdge_enum = 0;
pub const IMAQdxEdge_enum_IMAQdxEdgeFalling: IMAQdxEdge_enum = 1;
pub const IMAQdxEdge_enum_IMAQdxEdgeGuard: IMAQdxEdge_enum = -1;
pub type IMAQdxEdge_enum = ::std::os::raw::c_int;
pub use self::IMAQdxEdge_enum as IMAQdxEdge;
pub const IMAQdxStatusSignalType_enum_IMAQdxStatusSignalTypeAcquisitionActive:
	IMAQdxStatusSignalType_enum = 0;
pub const IMAQdxStatusSignalType_enum_IMAQdxStatusSignalTypeAcquisitionDone:
	IMAQdxStatusSignalType_enum = 1;
pub const IMAQdxStatusSignalType_enum_IMAQdxStatusSignalTypeFrameStart:
	IMAQdxStatusSignalType_enum = 2;
pub const IMAQdxStatusSignalType_enum_IMAQdxStatusSignalTypeFrameDone: IMAQdxStatusSignalType_enum =
	3;
pub const IMAQdxStatusSignalType_enum_IMAQdxStatusSignalTypeBufferComplete:
	IMAQdxStatusSignalType_enum = 4;
pub const IMAQdxStatusSignalType_enum_IMAQdxStatusSignalTypeGuard: IMAQdxStatusSignalType_enum = -1;
pub type IMAQdxStatusSignalType_enum = ::std::os::raw::c_int;
pub use self::IMAQdxStatusSignalType_enum as IMAQdxStatusSignalType;
pub type FrameDoneEventCallbackPtr = ::std::option::Option<
	unsafe extern "C" fn(
		id: IMAQdxSession,
		bufferNumber: uInt32,
		callbackData: *mut ::std::os::raw::c_void,
	) -> uInt32,
>;
pub type PnpEventCallbackPtr = ::std::option::Option<
	unsafe extern "C" fn(
		id: IMAQdxSession,
		pnpEvent: IMAQdxPnpEvent,
		callbackData: *mut ::std::os::raw::c_void,
	) -> uInt32,
>;
pub type AttributeUpdatedEventCallbackPtr = ::std::option::Option<
	unsafe extern "C" fn(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		callbackData: *mut ::std::os::raw::c_void,
	),
>;
pub type IOSignalEdgeEventCallbackPtr = ::std::option::Option<
	unsafe extern "C" fn(
		id: IMAQdxSession,
		signalType: IMAQdxIOSignalType,
		signalNumber: uInt32,
		signalEdge: IMAQdxEdge,
		callbackData: *mut ::std::os::raw::c_void,
	) -> uInt32,
>;
pub type StatusSignalEventCallbackPtr = ::std::option::Option<
	unsafe extern "C" fn(
		id: IMAQdxSession,
		statusSignalType: IMAQdxStatusSignalType,
		callbackData: *mut ::std::os::raw::c_void,
	) -> uInt32,
>;
pub const IMAQdxError_enum_IMAQdxErrorSuccess: IMAQdxError_enum = 0;
pub const IMAQdxError_enum_IMAQdxErrorSystemMemoryFull: IMAQdxError_enum = -1074360320;
pub const IMAQdxError_enum_IMAQdxErrorInternal: IMAQdxError_enum = -1074360319;
pub const IMAQdxError_enum_IMAQdxErrorInvalidParameter: IMAQdxError_enum = -1074360318;
pub const IMAQdxError_enum_IMAQdxErrorInvalidPointer: IMAQdxError_enum = -1074360317;
pub const IMAQdxError_enum_IMAQdxErrorInvalidInterface: IMAQdxError_enum = -1074360316;
pub const IMAQdxError_enum_IMAQdxErrorInvalidRegistryKey: IMAQdxError_enum = -1074360315;
pub const IMAQdxError_enum_IMAQdxErrorInvalidAddress: IMAQdxError_enum = -1074360314;
pub const IMAQdxError_enum_IMAQdxErrorInvalidDeviceType: IMAQdxError_enum = -1074360313;
pub const IMAQdxError_enum_IMAQdxErrorNotImplemented: IMAQdxError_enum = -1074360312;
pub const IMAQdxError_enum_IMAQdxErrorCameraNotFound: IMAQdxError_enum = -1074360311;
pub const IMAQdxError_enum_IMAQdxErrorCameraInUse: IMAQdxError_enum = -1074360310;
pub const IMAQdxError_enum_IMAQdxErrorCameraNotInitialized: IMAQdxError_enum = -1074360309;
pub const IMAQdxError_enum_IMAQdxErrorCameraRemoved: IMAQdxError_enum = -1074360308;
pub const IMAQdxError_enum_IMAQdxErrorCameraRunning: IMAQdxError_enum = -1074360307;
pub const IMAQdxError_enum_IMAQdxErrorCameraNotRunning: IMAQdxError_enum = -1074360306;
pub const IMAQdxError_enum_IMAQdxErrorAttributeNotSupported: IMAQdxError_enum = -1074360305;
pub const IMAQdxError_enum_IMAQdxErrorAttributeNotSettable: IMAQdxError_enum = -1074360304;
pub const IMAQdxError_enum_IMAQdxErrorAttributeNotReadable: IMAQdxError_enum = -1074360303;
pub const IMAQdxError_enum_IMAQdxErrorAttributeOutOfRange: IMAQdxError_enum = -1074360302;
pub const IMAQdxError_enum_IMAQdxErrorBufferNotAvailable: IMAQdxError_enum = -1074360301;
pub const IMAQdxError_enum_IMAQdxErrorBufferListEmpty: IMAQdxError_enum = -1074360300;
pub const IMAQdxError_enum_IMAQdxErrorBufferListLocked: IMAQdxError_enum = -1074360299;
pub const IMAQdxError_enum_IMAQdxErrorBufferListNotLocked: IMAQdxError_enum = -1074360298;
pub const IMAQdxError_enum_IMAQdxErrorResourcesAllocated: IMAQdxError_enum = -1074360297;
pub const IMAQdxError_enum_IMAQdxErrorResourcesUnavailable: IMAQdxError_enum = -1074360296;
pub const IMAQdxError_enum_IMAQdxErrorAsyncWrite: IMAQdxError_enum = -1074360295;
pub const IMAQdxError_enum_IMAQdxErrorAsyncRead: IMAQdxError_enum = -1074360294;
pub const IMAQdxError_enum_IMAQdxErrorTimeout: IMAQdxError_enum = -1074360293;
pub const IMAQdxError_enum_IMAQdxErrorBusReset: IMAQdxError_enum = -1074360292;
pub const IMAQdxError_enum_IMAQdxErrorInvalidXML: IMAQdxError_enum = -1074360291;
pub const IMAQdxError_enum_IMAQdxErrorFileAccess: IMAQdxError_enum = -1074360290;
pub const IMAQdxError_enum_IMAQdxErrorInvalidCameraURLString: IMAQdxError_enum = -1074360289;
pub const IMAQdxError_enum_IMAQdxErrorInvalidCameraFile: IMAQdxError_enum = -1074360288;
pub const IMAQdxError_enum_IMAQdxErrorGenICamError: IMAQdxError_enum = -1074360287;
pub const IMAQdxError_enum_IMAQdxErrorFormat7Parameters: IMAQdxError_enum = -1074360286;
pub const IMAQdxError_enum_IMAQdxErrorInvalidAttributeType: IMAQdxError_enum = -1074360285;
pub const IMAQdxError_enum_IMAQdxErrorDLLNotFound: IMAQdxError_enum = -1074360284;
pub const IMAQdxError_enum_IMAQdxErrorFunctionNotFound: IMAQdxError_enum = -1074360283;
pub const IMAQdxError_enum_IMAQdxErrorLicenseNotActivated: IMAQdxError_enum = -1074360282;
pub const IMAQdxError_enum_IMAQdxErrorCameraNotConfiguredForListener: IMAQdxError_enum =
	-1074360281;
pub const IMAQdxError_enum_IMAQdxErrorCameraMulticastNotAvailable: IMAQdxError_enum = -1074360280;
pub const IMAQdxError_enum_IMAQdxErrorBufferHasLostPackets: IMAQdxError_enum = -1074360279;
pub const IMAQdxError_enum_IMAQdxErrorGiGEVisionError: IMAQdxError_enum = -1074360278;
pub const IMAQdxError_enum_IMAQdxErrorNetworkError: IMAQdxError_enum = -1074360277;
pub const IMAQdxError_enum_IMAQdxErrorCameraUnreachable: IMAQdxError_enum = -1074360276;
pub const IMAQdxError_enum_IMAQdxErrorHighPerformanceNotSupported: IMAQdxError_enum = -1074360275;
pub const IMAQdxError_enum_IMAQdxErrorInterfaceNotRenamed: IMAQdxError_enum = -1074360274;
pub const IMAQdxError_enum_IMAQdxErrorNoSupportedVideoModes: IMAQdxError_enum = -1074360273;
pub const IMAQdxError_enum_IMAQdxErrorSoftwareTriggerOverrun: IMAQdxError_enum = -1074360272;
pub const IMAQdxError_enum_IMAQdxErrorTestPacketNotReceived: IMAQdxError_enum = -1074360271;
pub const IMAQdxError_enum_IMAQdxErrorCorruptedImageReceived: IMAQdxError_enum = -1074360270;
pub const IMAQdxError_enum_IMAQdxErrorCameraConfigurationHasChanged: IMAQdxError_enum = -1074360269;
pub const IMAQdxError_enum_IMAQdxErrorCameraInvalidAuthentication: IMAQdxError_enum = -1074360268;
pub const IMAQdxError_enum_IMAQdxErrorUnknownHTTPError: IMAQdxError_enum = -1074360267;
pub const IMAQdxError_enum_IMAQdxErrorKernelDriverUnavailable: IMAQdxError_enum = -1074360266;
pub const IMAQdxError_enum_IMAQdxErrorPixelFormatDecoderUnavailable: IMAQdxError_enum = -1074360265;
pub const IMAQdxError_enum_IMAQdxErrorFirmwareUpdateNeeded: IMAQdxError_enum = -1074360264;
pub const IMAQdxError_enum_IMAQdxErrorFirmwareUpdateRebootNeeded: IMAQdxError_enum = -1074360263;
pub const IMAQdxError_enum_IMAQdxErrorLightingCurrentOutOfRange: IMAQdxError_enum = -1074360262;
pub const IMAQdxError_enum_IMAQdxErrorUSB3VisionError: IMAQdxError_enum = -1074360261;
pub const IMAQdxError_enum_IMAQdxErrorInvalidU3VUSBDescriptor: IMAQdxError_enum = -1074360260;
pub const IMAQdxError_enum_IMAQdxErrorU3VInvalidControlInterface: IMAQdxError_enum = -1074360259;
pub const IMAQdxError_enum_IMAQdxErrorU3VControlInterfaceError: IMAQdxError_enum = -1074360258;
pub const IMAQdxError_enum_IMAQdxErrorU3VInvalidEventInterface: IMAQdxError_enum = -1074360257;
pub const IMAQdxError_enum_IMAQdxErrorU3VEventInterfaceError: IMAQdxError_enum = -1074360256;
pub const IMAQdxError_enum_IMAQdxErrorU3VInvalidStreamInterface: IMAQdxError_enum = -1074360255;
pub const IMAQdxError_enum_IMAQdxErrorU3VStreamInterfaceError: IMAQdxError_enum = -1074360254;
pub const IMAQdxError_enum_IMAQdxErrorU3VUnsupportedConnectionSpeed: IMAQdxError_enum = -1074360253;
pub const IMAQdxError_enum_IMAQdxErrorU3VInsufficientPower: IMAQdxError_enum = -1074360252;
pub const IMAQdxError_enum_IMAQdxErrorU3VInvalidMaxCurrent: IMAQdxError_enum = -1074360251;
pub const IMAQdxError_enum_IMAQdxErrorBufferIncompleteData: IMAQdxError_enum = -1074360250;
pub const IMAQdxError_enum_IMAQdxErrorCameraAcquisitionConfigFailed: IMAQdxError_enum = -1074360249;
pub const IMAQdxError_enum_IMAQdxErrorCameraClosePending: IMAQdxError_enum = -1074360248;
pub const IMAQdxError_enum_IMAQdxErrorSoftwareFault: IMAQdxError_enum = -1074360247;
pub const IMAQdxError_enum_IMAQdxErrorCameraPropertyInvalid: IMAQdxError_enum = -1074360246;
pub const IMAQdxError_enum_IMAQdxErrorJumboFramesNotEnabled: IMAQdxError_enum = -1074360245;
pub const IMAQdxError_enum_IMAQdxErrorBayerPixelFormatNotSelected: IMAQdxError_enum = -1074360244;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqImageSizeNotAligned: IMAQdxError_enum = -1074360243;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqChunkDataSizeTooBig: IMAQdxError_enum = -1074360242;
pub const IMAQdxError_enum_IMAQdxErrorBufferNotExtracted: IMAQdxError_enum = -1074360241;
pub const IMAQdxError_enum_IMAQdxErrorDuplicateImageInRing: IMAQdxError_enum = -1074360240;
pub const IMAQdxError_enum_IMAQdxErrorImageNotConfiguredInRing: IMAQdxError_enum = -1074360239;
pub const IMAQdxError_enum_IMAQdxErrorMismatchedBorders: IMAQdxError_enum = -1074360238;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqDecodeRequired: IMAQdxError_enum = -1074360237;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqNonZeroBorder: IMAQdxError_enum = -1074360236;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqWidthNotAligned: IMAQdxError_enum = -1074360235;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqOnly: IMAQdxError_enum = -1074360234;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqNotEnoughImages: IMAQdxError_enum = -1074360233;
pub const IMAQdxError_enum_IMAQdxErrorImageDisposed: IMAQdxError_enum = -1074360232;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqPaddingCapabilityExceeded: IMAQdxError_enum =
	-1074360231;
pub const IMAQdxError_enum_IMAQdxErrorNIGEVUpdateRequired: IMAQdxError_enum = -1074360230;
pub const IMAQdxError_enum_IMAQdxErrorPacketSizeOver9000: IMAQdxError_enum = -1074360229;
pub const IMAQdxError_enum_IMAQdxErrorAttributeSetFailure: IMAQdxError_enum = -1074360228;
pub const IMAQdxError_enum_IMAQdxErrorFirmwareUpdatePowerCycleNeeded: IMAQdxError_enum =
	-1074360227;
pub const IMAQdxError_enum_IMAQdxErrorLensCommunicationFailure: IMAQdxError_enum = -1074360226;
pub const IMAQdxError_enum_IMAQdxErrorBIOSIncompatible: IMAQdxError_enum = -1074360225;
pub const IMAQdxError_enum_IMAQdxErrorAdministrativePrivilegesRequired: IMAQdxError_enum =
	-1074360224;
pub const IMAQdxError_enum_IMAQdxErrorNIIMAQUpdateRequired: IMAQdxError_enum = -1074360223;
pub const IMAQdxError_enum_IMAQdxErrorCannotRenameBoardWhileSessionOpen: IMAQdxError_enum =
	-1074360222;
pub const IMAQdxError_enum_IMAQdxErrorRingAcqInvalidPacketSize: IMAQdxError_enum = -1074360221;
pub const IMAQdxError_enum_IMAQdxErrorBufferNumberOutOfRange: IMAQdxError_enum = -1074360220;
pub const IMAQdxError_enum_IMAQdxErrorUnknownTapGeometry: IMAQdxError_enum = -1074360219;
pub const IMAQdxError_enum_IMAQdxErrorCLGenICamProbeTimeout: IMAQdxError_enum = -1074360218;
pub const IMAQdxError_enum_IMAQdxErrorAcquisitionTerminated: IMAQdxError_enum = -1074360217;
pub const IMAQdxError_enum_IMAQdxErrorInvalidDynamicImageChange: IMAQdxError_enum = -1074360216;
pub const IMAQdxError_enum_IMAQdxErrorIncompatibleImageDataRing: IMAQdxError_enum = -1074360215;
pub const IMAQdxError_enum_IMAQdxErrorGenICamPersistence: IMAQdxError_enum = -1074360214;
pub const IMAQdxError_enum_IMAQdxErrorAcquisitionNotSupported: IMAQdxError_enum = -1074360213;
pub const IMAQdxError_enum_IMAQdxErrorFirmwareVersionMismatch: IMAQdxError_enum = -1074360212;
pub const IMAQdxError_enum_IMAQdxErrorDefaultFpgaDownloadNotAllowedWhileFpgaBusy: IMAQdxError_enum =
	-1074360211;
pub const IMAQdxError_enum_IMAQdxErrorLinkConfigurationMismatch: IMAQdxError_enum = -1074360210;
pub const IMAQdxError_enum_IMAQdxErrorIncompatibleBitfile: IMAQdxError_enum = -1074360209;
pub const IMAQdxError_enum_IMAQdxErrorAcquisitionOverflow: IMAQdxError_enum = -1074360208;
pub const IMAQdxError_enum_IMAQdxErrorLinkConfigExtensionTimeout: IMAQdxError_enum = -1074360207;
pub const IMAQdxError_enum_IMAQdxErrorLinkConfigLinkRateTimeout: IMAQdxError_enum = -1074360206;
pub const IMAQdxError_enum_IMAQdxErrorLinkRateNotSupported: IMAQdxError_enum = -1074360205;
pub const IMAQdxError_enum_IMAQdxErrorInvalidExtensionLinkCount: IMAQdxError_enum = -1074360204;
pub const IMAQdxError_enum_IMAQdxErrorLinkConfigMasterReadyTimeout: IMAQdxError_enum = -1074360203;
pub const IMAQdxError_enum_IMAQdxErrorGuard: IMAQdxError_enum = -1;
pub type IMAQdxError_enum = ::std::os::raw::c_int;
pub use self::IMAQdxError_enum as IMAQdxError;
unsafe extern "C" {
	pub fn IMAQdxSnap(id: IMAQdxSession, image: *mut Image) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxConfigureGrab(id: IMAQdxSession) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGrab(
		id: IMAQdxSession,
		image: *mut Image,
		waitForNextBuffer: bool32,
		actualBufferNumber: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxSequence(id: IMAQdxSession, images: *mut *mut Image, count: uInt32)
	-> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxDiscoverEthernetCameras(
		address: *const ::std::os::raw::c_char,
		timeout: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxEnumerateCameras(
		cameraInformationArray: *mut IMAQdxCameraInformation,
		count: *mut uInt32,
		connectedOnly: bool32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxResetCamera(name: *const ::std::os::raw::c_char, resetAll: bool32) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxOpenCamera(
		name: *const ::std::os::raw::c_char,
		mode: IMAQdxCameraControlMode,
		id: *mut IMAQdxSession,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxCloseCamera(id: IMAQdxSession) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxConfigureAcquisition(
		id: IMAQdxSession,
		continuous: bool32,
		bufferCount: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxStartAcquisition(id: IMAQdxSession) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetImage(
		id: IMAQdxSession,
		image: *mut Image,
		mode: IMAQdxBufferNumberMode,
		desiredBufferNumber: uInt32,
		actualBufferNumber: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetImageData(
		id: IMAQdxSession,
		buffer: *mut ::std::os::raw::c_void,
		bufferSize: uInt32,
		mode: IMAQdxBufferNumberMode,
		desiredBufferNumber: uInt32,
		actualBufferNumber: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxStopAcquisition(id: IMAQdxSession) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxUnconfigureAcquisition(id: IMAQdxSession) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxEnumerateVideoModes(
		id: IMAQdxSession,
		videoModeArray: *mut IMAQdxVideoMode,
		count: *mut uInt32,
		currentMode: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxEnumerateAttributes(
		id: IMAQdxSession,
		attributeInformationArray: *mut IMAQdxAttributeInformation,
		count: *mut uInt32,
		root: *const ::std::os::raw::c_char,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttribute(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		type_: IMAQdxValueType,
		value: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxSetAttribute(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		type_: IMAQdxValueType,
		...
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeMinimum(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		type_: IMAQdxValueType,
		value: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeMaximum(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		type_: IMAQdxValueType,
		value: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeIncrement(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		type_: IMAQdxValueType,
		value: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeType(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		type_: *mut IMAQdxAttributeType,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxIsAttributeReadable(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		readable: *mut bool32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxIsAttributeWritable(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		writable: *mut bool32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxEnumerateAttributeValues(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		list: *mut IMAQdxEnumItem,
		size: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeTooltip(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		tooltip: *mut ::std::os::raw::c_char,
		length: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeUnits(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		units: *mut ::std::os::raw::c_char,
		length: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxRegisterFrameDoneEvent(
		id: IMAQdxSession,
		bufferInterval: uInt32,
		callbackFunction: FrameDoneEventCallbackPtr,
		callbackData: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxRegisterPnpEvent(
		id: IMAQdxSession,
		event: IMAQdxPnpEvent,
		callbackFunction: PnpEventCallbackPtr,
		callbackData: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWriteRegister(id: IMAQdxSession, offset: uInt32, value: uInt32) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxReadRegister(id: IMAQdxSession, offset: uInt32, value: *mut uInt32)
	-> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWriteMemory(
		id: IMAQdxSession,
		offset: uInt32,
		values: *const ::std::os::raw::c_char,
		count: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxReadMemory(
		id: IMAQdxSession,
		offset: uInt32,
		values: *mut ::std::os::raw::c_char,
		count: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetErrorString(
		error: IMAQdxError,
		message: *mut ::std::os::raw::c_char,
		messageLength: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWriteAttributes(
		id: IMAQdxSession,
		filename: *const ::std::os::raw::c_char,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxReadAttributes(
		id: IMAQdxSession,
		filename: *const ::std::os::raw::c_char,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxResetEthernetCameraAddress(
		name: *const ::std::os::raw::c_char,
		address: *const ::std::os::raw::c_char,
		subnet: *const ::std::os::raw::c_char,
		gateway: *const ::std::os::raw::c_char,
		timeout: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxEnumerateAttributes2(
		id: IMAQdxSession,
		attributeInformationArray: *mut IMAQdxAttributeInformation,
		count: *mut uInt32,
		root: *const ::std::os::raw::c_char,
		visibility: IMAQdxAttributeVisibility,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeVisibility(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		visibility: *mut IMAQdxAttributeVisibility,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeDescription(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		description: *mut ::std::os::raw::c_char,
		length: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetAttributeDisplayName(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		displayName: *mut ::std::os::raw::c_char,
		length: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxDispose(buffer: *mut ::std::os::raw::c_void) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxRegisterAttributeUpdatedEvent(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		callbackFunction: AttributeUpdatedEventCallbackPtr,
		callbackData: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxEnumerateAttributes3(
		id: IMAQdxSession,
		attributeInformationArray: *mut IMAQdxAttributeInformation,
		count: *mut uInt32,
		root: *const ::std::os::raw::c_char,
		visibility: IMAQdxAttributeVisibility,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxConfigureRingAcquisition(
		id: IMAQdxSession,
		continuous: bool32,
		images: *mut *mut Image,
		count: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxExtractImage(
		id: IMAQdxSession,
		mode: IMAQdxBufferNumberMode,
		desiredBufferNumber: uInt32,
		actualBufferNumber: *mut uInt32,
		timeout: Int32,
		releasePrevious: bool32,
		image: *mut *mut Image,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxReleaseImage(
		id: IMAQdxSession,
		image: *mut Image,
		bufferNumber: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxGetImage2(
		id: IMAQdxSession,
		image: *mut Image,
		mode: IMAQdxBufferNumberMode,
		desiredBufferNumber: uInt32,
		actualBufferNumber: *mut uInt32,
		timeoutMs: Int32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWriteRegister2(id: IMAQdxSession, offset: uInt64, value: uInt32) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxReadRegister2(
		id: IMAQdxSession,
		offset: uInt64,
		value: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWriteMemory2(
		id: IMAQdxSession,
		offset: uInt64,
		values: *const ::std::os::raw::c_char,
		count: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxReadMemory2(
		id: IMAQdxSession,
		offset: uInt64,
		values: *mut ::std::os::raw::c_char,
		count: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxSerialRead(
		id: IMAQdxSession,
		buffer: *mut Int8,
		bufferSize: *mut uInt32,
		timeoutMs: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxSerialReadBytes(
		id: IMAQdxSession,
		buffer: *mut Int8,
		bufferSize: *mut uInt32,
		timeoutMs: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxSerialWrite(
		id: IMAQdxSession,
		buffer: *mut Int8,
		bufferSize: *mut uInt32,
		timeoutMs: uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxSerialFlush(id: IMAQdxSession) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxRegisterIOSignalEdgeEvent(
		id: IMAQdxSession,
		signalType: IMAQdxIOSignalType,
		signalNumber: uInt32,
		signalEdge: IMAQdxEdge,
		callbackFunction: IOSignalEdgeEventCallbackPtr,
		callbackData: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxRegisterStatusSignalEvent(
		id: IMAQdxSession,
		statusSignalType: IMAQdxStatusSignalType,
		callbackFunction: StatusSignalEventCallbackPtr,
		callbackData: *mut ::std::os::raw::c_void,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWaitForFrameDone(
		id: IMAQdxSession,
		timeout: Int32,
		bufferNumber: *mut uInt32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWaitForPnpEvent(
		id: IMAQdxSession,
		event: IMAQdxPnpEvent,
		timeout: Int32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWaitForAttributeUpdated(
		id: IMAQdxSession,
		name: *const ::std::os::raw::c_char,
		timeout: Int32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWaitForIOSignalEdge(
		id: IMAQdxSession,
		signalType: IMAQdxIOSignalType,
		signalNumber: uInt32,
		signalEdge: IMAQdxEdge,
		timeout: Int32,
	) -> IMAQdxError;
}
unsafe extern "C" {
	pub fn IMAQdxWaitForStatusSignal(
		id: IMAQdxSession,
		statusSignalType: IMAQdxStatusSignalType,
		timeout: Int32,
	) -> IMAQdxError;
}
